### ISSUE TITLE
Refactor componentWillReceiveProps in Lightbox component

### ISSUE THREAD

**Issue by 7ack7** [jossmac/react-images#308]
React 16.9.0 warns of the impending deprecation of componentWillReceiveProps:

> react-dom.development.js:11494 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
>
> Please update the following components: Lightbox

**Comment by apepper** [comment]
Fixed in https://github.com/jossmac/react-images/pull/324 => can be closed.

**Comment by nicoladl** [comment]
I still see the warnings with `"react-images": "^1.1.0-beta.2"`
I'm missing something?

**Comment by davwheat** [comment]
It's possible some still remain because the pulls were created before other changes

**Comment by nicoladl** [comment]
I'm not able to open a pr because I can't find the `componentWillMount` and `componentWillReceiveProps` in the code.

![Screenshot 2020-01-17 at 10 06 08](https://user-images.githubusercontent.com/2022727/72598940-1bb07d80-3911-11ea-84b9-e87acf87248d.png)

**Comment by apepper** [comment]
@nicoladl : Are you sure, you installed `1.1.0-beta.2`? Because greping for `componentWillReceiveProps` in the installed node package does not reveal any hits - at least on my machine.

**Comment by nicoladl** [comment]
![Screenshot 2020-01-17 at 10 36 01](https://user-images.githubusercontent.com/2022727/72601170-32f16a00-3915-11ea-9637-d6f3bc603946.png)

😊

**Comment by davwheat** [comment]
But did you `npm install`?

**Comment by nicoladl** [comment]
What do you mean?
Of course that I did `npm install react-images`
