### ISSUE TITLE
No types

### ISSUE THREAD

**Issue by JClackett** [jossmac/react-images#345]
yarn add react-images

v1.1.0-beta.2

inspect node_modules/react-images, there are no types even though it references ./index.d.ts

**Comment by JClackett** [comment]
please can you release another version to NPM :)

**Comment by davwheat** [comment]
Can you check if it's present in v1.1.0-beta.3 which I just published?

Thanks!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/27/20,
05:47:24 PM

**Comment by JClackett** [comment]
Still not there :( 

All i have is this...

<img width="244" alt="Screenshot 2020-01-27 at 18 56 01" src="https://user-images.githubusercontent.com/12549124/73200284-c2c5be00-4136-11ea-99cf-319910dff1c2.png">

Something with your publish step is not including all the files, potentially in your package.json you should include the declation file in the "files" array..

```
  "files": [
    "dist",
    "lib",
    "src",
    "index.d.ts"
  ],  
```

**Comment by davwheat** [comment]
Sorry! I've never done typings before so this is all brand new to me!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/27/20,
06:55:50 PM

**Comment by davwheat** [comment]
Sorry! I've never done typings before so this is all brand new to me!

It seems it's already in there:

```js
  "files": [
    "dist",
    "lib",
    "src",
    "index.d.ts"
  ],
```

**Comment by doublejosh** [comment]
Looks like the types file only exports a `Lightbox` and `Image` and is missing both `Modal` and `ModalGateway` ...am I missing something?

**Comment by doublejosh** [comment]
Believe I found it, the other entry in `package.json`...

SHOULD BE: `"types": "index.d.ts",`
CURRENTLY: `"types": "./index.d.ts",`
