### ISSUE TITLE
closeOnBackdropClick works on backdrop to the left and right of image, but not above and below image

### ISSUE THREAD

**Issue by tywmick** [jossmac/react-images#351]
Not sure if #313 would fix this—I'm not able to look closely at it right now.

**Steps to reproduce the behavior:**

Tested on Chrome with npm versions `1.1.0-beta.3`, `1.1.0-beta.2`, and `1.0.0`. Also tested `1.1.0-beta.3` on Firefox and Safari. Here's my JSX:

```jsx
{/* Lightbox gallery */}
<ModalGateway>
  {lightboxOpen && (
    <Modal
      onClose={toggleLightbox}
      allowFullscreen={false}
      closeOnBackdropClick={true}
    >
      <Carousel
        currentIndex={lightboxIndex}
        views={photoSources}
      />
    </Modal>
  )}
</ModalGateway>
```

My state and toggle function:

```jsx
// Lightbox gallery
const [lightboxIndex, setLightboxIndex] = useState(0);
const [lightboxOpen, setLightboxOpen] = useState(false);
const toggleLightbox = index => {
  setLightboxIndex(index);
  setLightboxOpen(!lightboxOpen);
};
```

**Expected behavior:**

Clicks on the backdrop on all sides of the image ought to close the modal.

**Actual behavior:**

Only backdrop clicks to the right and left of the image close the modal, not backdrop clicks above and below the image.

![react-images-backdrop-click-bug](https://user-images.githubusercontent.com/5317080/75055103-fc6db880-5499-11ea-9193-1c3af165513f.gif)

**Comment by lsnryszardb** [comment]
This worked for me as a temporary fix:
```css
.react-images__view {
    display: flex;
    height: 100vh;
    align-items: center;
    justify-content: center;
}
```

**Comment by tywmick** [comment]
That did it—thanks, @lsnryszardb!

**Comment by alec-francis** [comment]
I'm running version 1.1.3 and the opposite is happening for me.

Clicking above and below the image will dismiss the modal while clicking to the left or right of the image does nothing.

**Comment by davwheat** [comment]
I fixed this in the latest version, I believe.

>

**Comment by durdevic** [comment]
@davwheat I updated to 1.1.3 and the issue still sort of exists. 

What I see here is that dismiss only happens when you click on the _red_ areas(**react-images__header**, **react-images__footer** and **react-images__pager**) but not on the _green_ area (**react-images__positioner**). 

Maybe you have another approach how to do it, but I believe this causes the issue right now. 

Screenshot:
![Screenshot 2020-05-01 at 14 13 36](https://user-images.githubusercontent.com/2753836/80804617-f856c900-8bb5-11ea-90e8-926dc5ed1196.png)

**Comment by davwheat** [comment]
This should be a fairly easy fix... (that's what they all say...!)

**Comment by davwheat** [comment]
@durdevic Can you check if this is still present in 1.1.4?

**Comment by durdevic** [comment]
@davwheat Haha, sorry to break it to you mate for the "easy to fix" comment, but after the update it broke and I got this:

``` console
index.js:1 The above error occurred in the <FooterCaption> component:
    in FooterCaption (created by Footer)
    in div (created by css)
    in css (created by Base)
    in Base (created by Div)
    in Div (created by css)
    in css (created by Footer)
    in Footer (created by Carousel)
    in div (created by css)
    in css (created by Base)
    in Base (created by Div)
    in Div (created by css)
    in css (created by Container)
    in Container (created by Carousel)
    in Carousel (at CarouselModal.js:27)
    in div (created by css)
    in css (created by Base)
    in Base (created by Div)
    in Div (created by css)
    in css (created by Dialog)
    in div (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by ForwardRef)
    in ForwardRef (created by Dialog)
    in Dialog (created by Modal)
    in div (created by css)
    in css (created by Base)
    in Base (created by Div)
    in Div (created by css)
    in css (created by Positioner)
    in Positioner (created by Transition)
    in Transition (created by SlideUp)
    in SlideUp (created by Modal)
    in div (created by FullScreen)
    in FullScreen (created by Modal)
    in Modal (at CarouselModal.js:10)
    in FirstChild (created by TransitionGroup)
    in TransitionGroup (created by ModalGateway)
    in ModalGateway (at CarouselModal.js:8)
    in CarouselModal (at URLPreviewSection.js:55)
    in URLPreviewSection (at DefaultMessage.js:90)
    in div (created by styled.div)
    in styled.div (at DefaultMessage.js:175)
    in div (created by styled.div)
    in styled.div (at DefaultMessage.js:166)
    in div (created by styled.div)
    in styled.div (at DefaultMessage.js:164)
    in DefaultMessage (at FolderContainer.js:747)
    in div (created by styled.div)
    in styled.div (at FolderContainer.js:732)
    in div (at FolderContainer.js:730)
    in div (created by styled.div)
    in styled.div (at FolderContainer.js:723)
    in section (at MyDropzone.js:34)
    in MyDropzone (at FolderContainer.js:843)
    in div (created by styled.div)
    in styled.div (at FolderContainer.js:799)
    in FolderContainer (at DnDComponent.js:269)
    in div (created by styled.div)
    in styled.div (at DnDComponent.js:314)
    in section (created by styled.section)
    in styled.section (at DnDComponent.js:313)
    in Unknown (at DnDComponent.js:312)
    in ReactHotkeys (at DnDComponent.js:293)
    in DnDComponent (at Home.js:29)
    in div (created by styled.div)
    in styled.div (at Home.js:28)
    in Home (created by Context.Consumer)
    in Route (at Routes.js:19)
    in Switch (at Routes.js:15)
    in Router (created by BrowserRouter)
    in BrowserRouter (at Routes.js:14)
    in Routes (at App.js:129)
    in GraphqlErrorBoundary (at App.js:128)
    in ApolloProvider (at App.js:127)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (at src/index.js:16)

React will try to recreate this component tree from scratch using the error boundary you provided, Home.
console.<computed> @ index.js:1
r @ react_devtools_backend.js:6
logCapturedError @ react-dom.development.js:19561
logError @ react-dom.development.js:19598
callback @ react-dom.development.js:20778
callCallback @ react-dom.development.js:12513
commitUpdateQueue @ react-dom.development.js:12534
commitLifeCycles @ react-dom.development.js:19892
commitLayoutEffects @ react-dom.development.js:22835
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
commitRootImpl @ react-dom.development.js:22573
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11062
commitRoot @ react-dom.development.js:22413
finishSyncRender @ react-dom.development.js:21839
performSyncWorkOnRoot @ react-dom.development.js:21825
(anonymous) @ react-dom.development.js:11112
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11062
flushSyncCallbackQueueImpl @ react-dom.development.js:11107
flushSyncCallbackQueue @ react-dom.development.js:11095
discreteUpdates$1 @ react-dom.development.js:21925
discreteUpdates @ react-dom.development.js:1072
dispatchDiscreteEvent @ react-dom.development.js:4169
Home.js:12 componentDidCatch ReferenceError: string is not defined
    at FooterCaption (react-images.es.js:306)
    at renderWithHooks (react-dom.development.js:14826)
    at mountIndeterminateComponent (react-dom.development.js:17506)
    at beginWork (react-dom.development.js:18630)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at beginWork$1 (react-dom.development.js:23235)
    at performUnitOfWork (react-dom.development.js:22186)
    at workLoopSync (react-dom.development.js:22162)
    at performSyncWorkOnRoot (react-dom.development.js:21788)
    at react-dom.development.js:11112
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11062)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11107)
    at flushSyncCallbackQueue (react-dom.development.js:11095)
    at discreteUpdates$1 (react-dom.development.js:21925)
    at discreteUpdates (react-dom.development.js:1072)
    at dispatchDiscreteEvent (react-dom.development.js:4169)
Home.js:22 Just a normal error ReferenceError: string is not defined
    at FooterCaption (react-images.es.js:306)
    at renderWithHooks (react-dom.development.js:14826)
    at mountIndeterminateComponent (react-dom.development.js:17506)
    at beginWork (react-dom.development.js:18630)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at beginWork$1 (react-dom.development.js:23235)
    at performUnitOfWork (react-dom.development.js:22186)
    at workLoopSync (react-dom.development.js:22162)
    at performSyncWorkOnRoot (react-dom.development.js:21788)
    at react-dom.development.js:11112
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11062)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11107)
    at flushSyncCallbackQueue (react-dom.development.js:11095)
    at discreteUpdates$1 (react-dom.development.js:21925)
    at discreteUpdates (react-dom.development.js:1072)
    at dispatchDiscreteEvent (react-dom.development.js:4169)
```

**Comment by davwheat** [comment]
Fantastic.

**Comment by durdevic** [comment]
Okay, so following the "Can you check if this is still present in 1.1.4?" comment I updated to 1.1.4, and it was breaking, but now I saw that the **latest version is 1.1.6**. There it works perfectly! 😁 

Awesome job mate! Super quick fixing 💪

**Comment by davwheat** [comment]
Wow! It worked? That was surprising. I'm about to push out 1.1.7 😂 

I just found another issue which doesn't affect the use of the library's modals, but does affect you if you only use the carousel component.

**Comment by durdevic** [comment]
I updated to 1.1.7, everything still works! I am ok if you close this issue 😁 

P.S. Do you accept feature requests, and if yes, how can I let you know?

**Comment by davwheat** [comment]
Nice! Just create an issue and I'll see what I can do.

I don't usually get round to updating this package much, but these were pretty critical bugs, and lockdown is lockdown, after all.

**Comment by durdevic** [comment]
Haha, totally get you 👌  Hope you're managing this crazy scenario well.
